#### Keyboard Settings
keymap = """
xkb_keymap {
    xkb_keycodes { include "evdev+aliases(qwerty)" };
    xkb_types    { include "complete"              };
    xkb_compat   { include "complete"              };
    xkb_symbols  { include "pc+us+inet(evdev)+capslock(escape)+ctrl(swap_lalt_lctl)" };
};
"""

repeat-rate = { rate = 20, delay = 200 }


#### Visual Features
workspace-display-order = "sorted"
show-bar = true
show-titles = false


#### Behavior Features
middle-click-paste = false
focus-follows-mouse = true
window-management-key = "Super_L"
pointer-revert-key = "NoSymbol"
unstable-mouse-follows-focus = true
fallback-output-mode = "focus"
use-hardware-cursor = false


#### Startup Actions
on-graphics-initialized = [
# { type = "exec", exec = { prog = "jay", args = ["run-privileged", "waybar", "-c", "/home/arjungore/.config/waybar/config_jay.jsonc", "-s", "/home/arjungore/.config/waybar/style_jay.css"] } },
{ type = "exec", exec = "mako" },
{ type = "exec", exec = { prog = "swaybg", args = ["--output", "DP-2", "-i", "/home/arjungore/projects/snow/assets/photos/jake.png", "-m", "fill", "--output", "HDMI-A-1", "-i", "/home/arjungore/projects/snow/assets/photos/finn.png", "-m", "fill"], privileged = true } },
{ type = "exec", exec = { prog = "swayidle", args = ["-w", "timeout", "600", "swaylock -f", "before-sleep", "swaylock -f"], privileged = true } },

{ type = "show-workspace", name = "1",  output.name = "left"  },
{ type = "show-workspace", name = "2",  output.name = "left"  },
{ type = "show-workspace", name = "3",  output.name = "left"  },
{ type = "show-workspace", name = "4",  output.name = "left"  },
{ type = "show-workspace", name = "5",  output.name = "left"  },

{ type = "show-workspace", name = "6",  output.name = "right" },
{ type = "show-workspace", name = "7",  output.name = "right" },
{ type = "show-workspace", name = "8",  output.name = "right" },
{ type = "show-workspace", name = "9",  output.name = "right" },
{ type = "show-workspace", name = "10", output.name = "right" }
]


#### Idle Actions
idle = {
    minutes = 0,
}

on-idle = {
    type = "exec",
    exec = {
        prog = "swaylock",
        privileged = true,
    },
}


#### GPU
render-device = {
    pci-vendor = 0x1002,
    pci-model = 0x7480,
}

[[drm-devices]]
name = "dedicated"
match = {
    pci-vendor = 0x1002,
    pci-model = 0x7480,
}
gfx-api = "Vulkan"

[[drm-devices]]
name = "integrated"
match = {
    pci-vendor = 0x1002,
    pci-model = 0x164e,
}
gfx-api = "Vulkan"


#### Theme
[theme]
border-color = "#524f67"
border-width = 2

bar-height = 35
bar-bg-color = "#1f1d2e"
bar-status-text-color = "#e0def4"
focused-title-bg-color = "#403d52"
focused-title-text-color = "#e0def4"
captured-focused-title-bg-color = "#403d52"
captured-unfocused-title-bg-color = "#1f1d2e"
focused-inactive-title-bg-color = "#1f1d2e"
focused-inactive-title-text-color = "#6e6a86"
unfocused-title-bg-color = "#1f1d2e"
unfocused-title-text-color = "#6e6a86"
separator-color = "#1f1d2e"
font = "MesloLGS Nerd Font Mono Bold 15"

[status]
format = "i3bar"
exec = { prog = "i3status-rs", args = ["/home/arjungore/.config/i3status-rust/config.toml"], privileged = true }
# exec = "i3status-rs"
i3bar-separator = " "


#### Shortcuts
[shortcuts]

## Launching Apps
logo-Return             = { type = "exec", exec = { prog = "wezterm", privileged = true} }
logo-shift-Return       = { type = "exec", exec = "wezterm" }
logo-p                  = { type = "exec", exec = { prog = "wofi", args = ["--show", "drun"], privileged = true }}
logo-b                  = { type = "exec", exec = "zen" }
logo-shift-b            = { type = "exec", exec = "google-chrome-stable" }
logo-f                  = { type = "exec", exec = "thunar" }
logo-c                  = { type = "exec", exec = "code" }
logo-l                  = "open-control-center"
logo-u                  = "warp-mouse-to-focus"

logo-s                  = [ 
{ type = "exec", exec = "spotify" },
{ type = "show-workspace", name = "10",  output.name = "right" }
]

logo-d                  = [
{ type = "exec", exec = "equibop" },
{ type = "show-workspace", name = "7",  output.name = "right" }
]

## System Actions
logo-q                  = "close"
logo-shift-r            = "reload-config-toml"
logo-shift-e            = { type = "exec", exec = { prog = "bash", args = ["-lc", "~/.config/jay/exit-menu.sh"] } }
logo-shift-s            = { type = "exec", exec = { prog = "bash", args = ["-lc", "~/.config/jay/shutdown-menu.sh"] } }

logo-shift-p            = { type = "exec", exec = { prog = "bash", args = ["-lc", 'wayfreeze & PID=$!; sleep 0.1; grim -g "$(slurp)" - | wl-copy; kill "$PID" 2>/dev/null'], privileged = true } }
logo-shift-o            = { type = "exec", exec = { prog = "bash", args = ["-lc", 'wayfreeze & PID=$!; sleep 0.1; grim -g "$(slurp)" - | swappy -f -; kill "$PID" 2>/dev/null'], privileged = true } }

logo-F10                = { type = "exec", exec = { prog = "playerctl", args = ["-p", "spotify", "previous"], privileged = true }}
logo-F11                = { type = "exec", exec = { prog = "playerctl", args = ["-p", "spotify", "play-pause"], privileged = true }}
logo-F12                = { type = "exec", exec = { prog = "playerctl", args = ["-p", "spotify", "next"], privileged = true }}

XF86AudioRaiseVolume  = { type = "exec", exec = ["wpctl", "set-volume", "@DEFAULT_AUDIO_SINK@", "0.05+"] }
XF86AudioLowerVolume  = { type = "exec", exec = ["wpctl", "set-volume", "@DEFAULT_AUDIO_SINK@", "0.05-"] }
XF86AudioMute         = { type = "exec", exec = ["wpctl", "set-mute", "@DEFAULT_AUDIO_SINK@", "toggle"] }


## Window Movement/Management
logo-Left               = [
# "warp-mouse-to-focus",
    "focus-left"
]
logo-Right              = [
# "warp-mouse-to-focus",
    "focus-right"
]
logo-Up                 = [
# "warp-mouse-to-focus",
    "focus-up"
]
logo-Down               = [
# "warp-mouse-to-focus",
    "focus-down"
]

logo-shift-Left         = [
# "warp-mouse-to-focus",
    "move-left"
]
logo-shift-Right        = [
# "warp-mouse-to-focus",
    "move-right"
]
logo-shift-Up           = [
# "warp-mouse-to-focus",
    "move-up"
]
logo-shift-Down         = [
# "warp-mouse-to-focus",
    "move-down"
]

logo-ctrl-h             = "split-horizontal"
logo-ctrl-v             = "split-vertical"
logo-e                  = "toggle-split"
logo-shift-f            = "toggle-fullscreen"
logo-shift-space        = "toggle-floating"

## Workspaces
logo-1          = [ 
# "warp-mouse-to-focus",
{ type = "show-workspace", name = "1",  output.name = "left"  }
]
logo-2          = [ 
# "warp-mouse-to-focus",
{ type = "show-workspace", name = "2",  output.name = "left"  }
]
logo-3          = [ 
# "warp-mouse-to-focus",
{ type = "show-workspace", name = "3",  output.name = "left"  }
]
logo-4          = [ 
# "warp-mouse-to-focus",
{ type = "show-workspace", name = "4",  output.name = "left"  }
]
logo-5          = [ 
# "warp-mouse-to-focus",
{ type = "show-workspace", name = "5",  output.name = "left"  }
]
logo-6          = [ 
# "warp-mouse-to-focus",
{ type = "show-workspace", name = "6",  output.name = "right" }
]
logo-7          = [ 
# "warp-mouse-to-focus",
{ type = "show-workspace", name = "7",  output.name = "right" }
]
logo-8          = [ 
# "warp-mouse-to-focus",
{ type = "show-workspace", name = "8",  output.name = "right" }
]
logo-9          = [
# "warp-mouse-to-focus",
{ type = "show-workspace", name = "9",  output.name = "right" }
]
logo-0          = [
# "warp-mouse-to-focus",
{ type = "show-workspace", name = "10", output.name = "right" }
]

logo-shift-1    = [ 
# "warp-mouse-to-focus",
{ type = "move-to-workspace", name = "1" }, 
{ type = "move-to-output", workspace = "1", output.name = "left" },
{ type = "show-workspace", name = "1", output.name = "left" }
]
logo-shift-2    = [ 
# "warp-mouse-to-focus",
{ type = "move-to-workspace", name = "2" }, 
{ type = "move-to-output", workspace = "2", output.name = "left" },
{ type = "show-workspace", name = "2", output.name = "left" }
]
logo-shift-3    = [ 
# "warp-mouse-to-focus",
{ type = "move-to-workspace", name = "3" }, 
{ type = "move-to-output", workspace = "3", output.name = "left" },
{ type = "show-workspace", name = "3", output.name = "left" }
]
logo-shift-4    = [ 
# "warp-mouse-to-focus",
{ type = "move-to-workspace", name = "4" }, 
{ type = "move-to-output", workspace = "4", output.name = "left" },
{ type = "show-workspace", name = "4", output.name = "left" }
]
logo-shift-5    = [ 
# "warp-mouse-to-focus",
{ type = "move-to-workspace", name = "5" }, 
{ type = "move-to-output", workspace = "5", output.name = "left" },
{ type = "show-workspace", name = "5", output.name = "left" }
]
logo-shift-6    = [ 
# "warp-mouse-to-focus",
{ type = "move-to-workspace", name = "6" }, 
{ type = "move-to-output", workspace = "6", output.name = "right" },
{ type = "show-workspace", name = "6", output.name = "right" }
]
logo-shift-7    = [ 
# "warp-mouse-to-focus",
{ type = "move-to-workspace", name = "7" }, 
{ type = "move-to-output", workspace = "7", output.name = "right" },
{ type = "show-workspace", name = "7", output.name = "right" }
]
logo-shift-8    = [ 
# "warp-mouse-to-focus",
{ type = "move-to-workspace", name = "8" }, 
{ type = "move-to-output", workspace = "8", output.name = "right" },
{ type = "show-workspace", name = "8", output.name = "right" }
]
logo-shift-9    = [ 
# "warp-mouse-to-focus",
{ type = "move-to-workspace", name = "9" }, 
{ type = "move-to-output", workspace = "9", output.name = "right" },
{ type = "show-workspace", name = "9", output.name = "right" }
]
logo-shift-0    = [ 
# "warp-mouse-to-focus",
{ type = "move-to-workspace", name = "10" },
{ type = "move-to-output", workspace = "10", output.name = "right" },
{ type = "show-workspace", name = "10", output.name = "right" }
]


#### Resize Mode
[shortcuts.logo-r]
type = "multi"

[[shortcuts.logo-r.actions]]
name = "resize"
type = "push-mode"

[modes.resize.shortcuts.Down]
dy2 = 100
type = "resize"

[modes.resize.shortcuts.Left]
dx1 = -100
type = "resize"

[modes.resize.shortcuts.Right]
dx2 = 100
type = "resize"

[modes.resize.shortcuts.Up]
dy1 = -100
type = "resize"

[modes.resize.shortcuts.Escape]
type = "multi"

[[modes.resize.shortcuts.Escape.actions]]
cmd = "pop-mode"
type = "simple"

[modes.resize.shortcuts.logo-r]
type = "multi"

[[modes.resize.shortcuts.logo-r.actions]]
cmd = "pop-mode"
type = "simple"


#### Inputs
[[inputs]]
tag = "mice"
match.is-pointer = true
natural-scrolling = true
accel-profile = "Flat"
accel-speed = -0.875


#### Monitors
[[outputs]]
name = "left"
match.connector = "DP-2"
x = 0
y = 0
mode = { width = 2560, height = 1440, refresh-rate = 179.999 }
tearing.mode = "variant1"
vrr.mode = "never"

[[outputs]]
name = "right"
match.connector = "HDMI-A-1"
x = 2560
y = 360
mode = { width = 1920, height = 1080, refresh-rate = 100.000 }
tearing.mode = "never"
vrr.mode = "never"


#### Window Rules
[[windows]]
name = "discord"
match.x-class = "discord"
action = [
{ type = "move-to-workspace", name = "7" },
{ type = "move-to-output", workspace = "7", output.name = "right" },
{ type = "set-repeat-rate", rate = { rate = 20, delay = 200 } }
]

[[windows]]
name = "spotify"
match.x-class = "Spotify"
action = [
{ type = "move-to-workspace", name = "10" },
{ type = "move-to-output", workspace = "10", output.name = "right" },
{ type = "set-repeat-rate", rate = { rate = 20, delay = 200 } }
]

[[windows]]
name = "waywall"
match.app-id = "waywall"
action = [
{ type = "move-to-workspace", name = "1" },
{ type = "move-to-output", workspace = "1", output.name = "left" },
{ type = "set-repeat-rate", rate = { rate = 60, delay = 200} }
]

[[windows]]
name = "default"
match.types = "any"
action = [
{ type = "set-repeat-rate", rate = { rate = 20, delay = 200 } }
]
